import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "./providers/SessionProvider";
import { ThemeProvider } from "next-themes";
import { LanguageProvider } from "./context/LanguageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} font-sans`}>
        <ThemeProvider
          attribute="class" // penting: untuk mode gelap/terang via class di <html>
          defaultTheme="system"
          enableSystem={true}
          value={{
            light: "light",
            dark: "dark",
          }}
        >
          <NextAuthSessionProvider session={null}>
            <LanguageProvider>{children}</LanguageProvider>
          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
